name: pm25-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.1
  - pandas=2.1.3
  - scikit-learn=1.3.2
  - matplotlib=3.8.1
  - pytorch=2.1.0
  - tensorboard=2.15.1
  - jupyterlab=4.0.9
  - ipykernel=6.29.0
  - pip
